project:
  type: website

website:
  title: "Multilingual Site"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "English"
        href: en/index.qmd
      - text: "한국어"
        href: kr/index.qmd

format:
  html:
    css: styles.css
